on: push
jobs:
  myJob:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2 
      - run: npm install
        shell: bash
      - run: |
             export FETCH_LICENSE=true
             npm install -g @cyclonedx/cdxgen@8.6.0 && cdxgen -r -o bom.json
        shell: bash
      - run: |
            curl -k -X POST "https://dt-api.staging.cryptosoft.com/api/v1/bom" \
              -H "Content-Type: multipart/form-data" \
              -H "X-Api-Key: 1DMIXAnGtTIeTQDddlHSvpj6d3as174S " \
              -F "autoCreate=true" \
              -F "projectName=cs-backend1" \
              -F "projectVersion=1.0.0" \
              -F "bom=@bom.json" 
        shell: bash

